; ================================================================
;  Generated by basic2asm  -  BASIC -> MPASM transpiler
;  Target chip : PIC16F877A  (MIDRANGE core)
;  Clock       : 20000 kHz
;  Optimize    : SIZE
;  Flash       : 8192 words   RAM: 96 bytes
; ================================================================

        LIST    p=16f877a
        #include <p16f877a.inc>

; fuse configuration (config word @ 0x2007)
        __CONFIG _HS_OSC & _WDT_OFF & _PWRTE_ON & _BOREN_OFF & _LVP_OFF & _CPD_OFF & _CP_OFF

; --- RAM allocation (general purpose registers) ---
        cblock  0x20
            v_sample
            rt_d0
            rt_d1
            rt_d2
            rt_a
            rt_b
            rt_quot
            rt_rem
            rt_dec_val
            rt_dec_d
            rt_dec_started
        endc

; --- reset / interrupt vectors ---
        org     0x0000
        pagesel main
        goto    main

        org     0x0004
        retfie                     ; no ISR defined


main
; --- digital I/O setup (disable analog/comparators where present) ---
    ifdef CMCON
        banksel CMCON
        movlw   0x07
        movwf   CMCON
    endif
    ifdef CMCON0
        banksel CMCON0
        movlw   0x07
        movwf   CMCON0
    endif
        banksel PORTA
; --- ADC initialisation ---
        banksel ADCON1
        movlw   0x00               ; left justified, all AN pins analog, Vref=Vdd
        movwf   ADCON1
        banksel ADCON0
        movlw   0x41               ; ADCS=01 (Fosc/8), ADON=1
        movwf   ADCON0
        banksel PORTA
; hardware USART init @ 9600 baud (BRGH=1, SPBRG=129)
        banksel SPBRG
        movlw   0x81
        movwf   SPBRG
        movlw   0x24               ; TXSTA: BRGH=1, TXEN=1, async
        movwf   TXSTA
        banksel RCSTA
        movlw   0x90               ; RCSTA: SPEN=1, CREN=1
        movwf   RCSTA
        banksel PORTA
lbl_read_loop
; ADC read channel 0
        banksel ADCON0
        movlw   0x41               ; select channel, ADON
        movwf   ADCON0
        movlw   0x21
        movwf   rt_d0
dl0_0
        decfsz  rt_d0, f
        goto    dl0_0
        bsf     ADCON0, GO         ; start conversion
adcw_1
        btfsc   ADCON0, GO         ; wait for conversion
        goto    adcw_1
        banksel ADRESH
        movf    ADRESH, w          ; 8-bit result (high byte)
        banksel PORTA
; store sample
        movwf   v_sample
        movlw   0x41               ; 'A'
        call    _uart_tx_hw
        movlw   0x44               ; 'D'
        call    _uart_tx_hw
        movlw   0x43               ; 'C'
        call    _uart_tx_hw
        movlw   0x30               ; '0'
        call    _uart_tx_hw
        movlw   0x3D               ; '='
        call    _uart_tx_hw
        movf    v_sample, w        ; load sample
        call    _print_dec
        movlw   0x0D               ; CR
        call    _uart_tx_hw
        movlw   0x0A               ; LF
        call    _uart_tx_hw
; DELAY 250ms (~1250000 cycles @ 20000kHz)
        movlw   0x4B
        movwf   rt_d2
dl2_2
        movlw   0x4B
        movwf   rt_d1
dl2_1
        movlw   0x4A
        movwf   rt_d0
dl2_0
        decfsz  rt_d0, f
        goto    dl2_0
        decfsz  rt_d1, f
        goto    dl2_1
        decfsz  rt_d2, f
        goto    dl2_2
        goto    lbl_read_loop

; end of program: trap here
__halt
        goto    __halt

; ==================== runtime support ====================

; 8/8 divide: W = rt_a / rt_b (quotient), rt_rem = remainder
_div8
        clrf    rt_quot
        movf    rt_b, f
        btfsc   STATUS, Z
        goto    _div8_zero
        movf    rt_a, w
        movwf   rt_rem
_div8_loop
        movf    rt_b, w
        subwf   rt_rem, w          ; rem - b
        btfss   STATUS, C
        goto    _div8_done
        movwf   rt_rem
        incf    rt_quot, f
        goto    _div8_loop
_div8_done
        movf    rt_quot, w
        return  
_div8_zero
        movlw   0xFF
        movwf   rt_quot
        clrf    rt_rem
        movf    rt_quot, w
        return  

; hardware USART transmit of W
_uart_tx_hw
        banksel TXSTA
_uart_tx_hw_wait
        btfss   TXSTA, TRMT        ; wait for empty shift reg
        goto    _uart_tx_hw_wait
        banksel TXREG
        movwf   TXREG
        banksel PORTA
        return  

; print W as unsigned decimal (leading zeros suppressed)
_print_dec
        movwf   rt_dec_val
        clrf    rt_dec_started
        movf    rt_dec_val, w
        movwf   rt_a
        movlw   0x64
        movwf   rt_b
        call    _div8              ; digit = val / 100
        movwf   rt_dec_d
        movf    rt_rem, w
        movwf   rt_dec_val         ; val = val % 100
        movf    rt_dec_d, f
        btfss   STATUS, Z
        goto    _pd_print0         ; non-zero digit
        btfsc   rt_dec_started, 0
        goto    _pd_print0         ; already printing
        goto    _pd_skip0          ; suppress leading zero
_pd_print0
        bsf     rt_dec_started, 0
        movlw   0x30               ; '0'
        addwf   rt_dec_d, w        ; digit -> ASCII
        call    _uart_tx_hw
_pd_skip0
        movf    rt_dec_val, w
        movwf   rt_a
        movlw   0x0A
        movwf   rt_b
        call    _div8              ; digit = val / 10
        movwf   rt_dec_d
        movf    rt_rem, w
        movwf   rt_dec_val         ; val = val % 10
        movf    rt_dec_d, f
        btfss   STATUS, Z
        goto    _pd_print1         ; non-zero digit
        btfsc   rt_dec_started, 0
        goto    _pd_print1         ; already printing
        goto    _pd_skip1          ; suppress leading zero
_pd_print1
        bsf     rt_dec_started, 0
        movlw   0x30               ; '0'
        addwf   rt_dec_d, w        ; digit -> ASCII
        call    _uart_tx_hw
_pd_skip1
        movf    rt_dec_val, w
        movwf   rt_dec_d
        bsf     rt_dec_started, 0
        movf    rt_dec_d, f
        btfss   STATUS, Z
        goto    _pd_print2         ; non-zero digit
        btfsc   rt_dec_started, 0
        goto    _pd_print2         ; already printing
        goto    _pd_skip2          ; suppress leading zero
_pd_print2
        bsf     rt_dec_started, 0
        movlw   0x30               ; '0'
        addwf   rt_dec_d, w        ; digit -> ASCII
        call    _uart_tx_hw
_pd_skip2
        return  

        END
