; ================================================================
;  Generated by basic2asm  -  BASIC -> MPASM transpiler
;  Target chip : PIC12F509  (BASELINE core)
;  Clock       : 4000 kHz
;  Optimize    : SIZE
;  Flash       : 1024 words   RAM: 25 bytes
; ================================================================

        LIST    p=12f509
        #include <p12f509.inc>

; fuse configuration (config word @ 0xfff)
        __CONFIG _XT_OSC & _WDT_OFF & _CP_OFF & _MCLRE_ON

; --- RAM allocation (general purpose registers) ---
        cblock  0x7
            tris_gpio
            rt_d0
            rt_d1
            rt_d2
        endc

; --- reset / interrupt vectors ---
        org     0x0000
        goto    main


main
        movlw   0xFF               ; all inputs at reset
        movwf   tris_gpio
; OUTPUT GPIO.0
        movlw   0xFE
        andwf   tris_gpio, f       ; clear dir bit -> output
        movf    tris_gpio, w
        tris    6                  ; load TRIS
lbl_toggle_loop
        movf    GPIO, w
        xorlw   0x01               ; TOGGLE GP0
        movwf   GPIO
; DELAY 250ms (~250000 cycles @ 4000kHz)
        movlw   0x2C
        movwf   rt_d2
dl0_2
        movlw   0x2C
        movwf   rt_d1
dl0_1
        movlw   0x2B
        movwf   rt_d0
dl0_0
        decfsz  rt_d0, f
        goto    dl0_0
        decfsz  rt_d1, f
        goto    dl0_1
        decfsz  rt_d2, f
        goto    dl0_2
        goto    lbl_toggle_loop

; end of program: trap here
__halt
        goto    __halt

        END
