; ================================================================
;  Generated by basic2asm  -  BASIC -> MPASM transpiler
;  Target chip : PIC16F84A  (MIDRANGE core)
;  Clock       : 4000 kHz
;  Optimize    : SIZE
;  Flash       : 1024 words   RAM: 68 bytes
; ================================================================

        LIST    p=16f84a
        #include <p16f84a.inc>

; fuse configuration (config word @ 0x2007)
        __CONFIG _XT_OSC & _WDT_OFF & _PWRTE_ON & _CP_OFF

; --- RAM allocation (general purpose registers) ---
        cblock  0xC
            rt_d0
            rt_d1
            rt_d2
        endc

; --- reset / interrupt vectors ---
        org     0x0000
        goto    main

        org     0x0004
        retfie                     ; no ISR defined


main
; --- digital I/O setup (disable analog/comparators where present) ---
    ifdef CMCON
        banksel CMCON
        movlw   0x07
        movwf   CMCON
    endif
    ifdef CMCON0
        banksel CMCON0
        movlw   0x07
        movwf   CMCON0
    endif
    ifdef ANSEL
        banksel ANSEL
        clrf    ANSEL
    endif
    ifdef ANSELH
        banksel ANSELH
        clrf    ANSELH
    endif
    ifdef ADCON1
        banksel ADCON1
        movlw   0x06
        movwf   ADCON1
    endif
        banksel PORTA
; OUTPUT PORTB.0
        banksel TRISB
        bcf     TRISB, 0
        banksel PORTA
lbl_blink
        banksel PORTA
        bsf     PORTB, 0           ; HIGH RB0
; DELAY 500ms (~500000 cycles @ 4000kHz)
        movlw   0x37
        movwf   rt_d2
dl0_2
        movlw   0x37
        movwf   rt_d1
dl0_1
        movlw   0x37
        movwf   rt_d0
dl0_0
        decfsz  rt_d0, f
        goto    dl0_0
        decfsz  rt_d1, f
        goto    dl0_1
        decfsz  rt_d2, f
        goto    dl0_2
        banksel PORTA
        bcf     PORTB, 0           ; LOW RB0
; DELAY 500ms (~500000 cycles @ 4000kHz)
        movlw   0x37
        movwf   rt_d2
dl1_2
        movlw   0x37
        movwf   rt_d1
dl1_1
        movlw   0x37
        movwf   rt_d0
dl1_0
        decfsz  rt_d0, f
        goto    dl1_0
        decfsz  rt_d1, f
        goto    dl1_1
        decfsz  rt_d2, f
        goto    dl1_2
        goto    lbl_blink

; end of program: trap here
__halt
        goto    __halt

        END
