; ================================================================
;  Generated by basic2asm  -  BASIC -> MPASM transpiler
;  Target chip : PIC16F84A  (MIDRANGE core)
;  Clock       : 4000 kHz
;  Optimize    : SIZE
;  Flash       : 1024 words   RAM: 68 bytes
; ================================================================

        LIST    p=16f84a
        #include <p16f84a.inc>

; fuse configuration (config word @ 0x2007)
        __CONFIG _XT_OSC & _WDT_OFF & _PWRTE_ON & _CP_OFF

; --- RAM allocation (general purpose registers) ---
        cblock  0xC
            p_square_x
            v_i
            v_result
            for2_to
            rt_d0
            rt_d1
            rt_a
            rt_b
            rt_res
            rt_cnt
            tmp0
            tmp1
        endc

; --- reset / interrupt vectors ---
        org     0x0000
        goto    main

        org     0x0004
        retfie                     ; no ISR defined


main
; --- digital I/O setup (disable analog/comparators where present) ---
    ifdef CMCON
        banksel CMCON
        movlw   0x07
        movwf   CMCON
    endif
    ifdef CMCON0
        banksel CMCON0
        movlw   0x07
        movwf   CMCON0
    endif
    ifdef ANSEL
        banksel ANSEL
        clrf    ANSEL
    endif
    ifdef ANSELH
        banksel ANSELH
        clrf    ANSELH
    endif
    ifdef ADCON1
        banksel ADCON1
        movlw   0x06
        movwf   ADCON1
    endif
        banksel PORTA
; OUTPUT PORTB.0
        banksel TRISB
        bcf     TRISB, 0
        banksel PORTA
        movlw   0x01
        movwf   v_i
        movlw   0x0A
        movwf   for2_to            ; loop limit
for_0
        movf    v_i, w
        subwf   for2_to, w         ; to - var
        btfss   STATUS, C          ; exit when var > to
        goto    next_1
        movf    v_i, w             ; load i
        movwf   p_square_x         ; arg x
        call    sub_square
; store result
        movwf   v_result
        movf    v_result, w        ; load result
        movwf   tmp0               ; save lhs
        movlw   0x32
        movwf   tmp1               ; rhs
        movf    tmp0, w
        subwf   tmp1, w            ; rhs - lhs
        movlw   0x00
        btfss   STATUS, C
        movlw   0x01               ; > true
        iorlw   0x00               ; test condition
        btfsc   STATUS, Z
        goto    else_3
        banksel PORTA
        bsf     PORTB, 0           ; HIGH RB0
        goto    endif_2
else_3
        banksel PORTA
        bcf     PORTB, 0           ; LOW RB0
endif_2
; DELAY 100ms (~100000 cycles @ 4000kHz)
        movlw   0xB7
        movwf   rt_d1
dl4_1
        movlw   0xB6
        movwf   rt_d0
dl4_0
        decfsz  rt_d0, f
        goto    dl4_0
        decfsz  rt_d1, f
        goto    dl4_1
        incf    v_i, f             ; var++
        goto    for_0
next_1
; END
end_5
        goto    end_5

; end of program: trap here
__halt
        goto    __halt

; FUNCTION square
sub_square
        movf    p_square_x, w      ; load x
        movwf   tmp0               ; save lhs
        movf    p_square_x, w      ; load x
        movwf   rt_b               ; rhs
        movf    tmp0, w
        movwf   rt_a               ; lhs
        call    _mul8
        return  
        return  

; ==================== runtime support ====================

; 8x8 multiply (low byte): W = rt_a * rt_b
_mul8
        clrf    rt_res
        movf    rt_b, w
        movwf   rt_cnt
_mul8_loop
        movf    rt_cnt, f
        btfsc   STATUS, Z
        goto    _mul8_done
        movf    rt_a, w
        addwf   rt_res, f
        decf    rt_cnt, f
        goto    _mul8_loop
_mul8_done
        movf    rt_res, w
        return  

        END
