; ================================================================
;  Generated by basic2asm  -  BASIC -> MPASM transpiler
;  Target chip : PIC16F84A  (MIDRANGE core)
;  Clock       : 4000 kHz
;  Optimize    : SIZE
;  Flash       : 1024 words   RAM: 68 bytes
; ================================================================

        LIST    p=16f84a
        #include <p16f84a.inc>

; fuse configuration (config word @ 0x2007)
        __CONFIG _XT_OSC & _WDT_OFF & _PWRTE_ON & _CP_OFF

; --- RAM allocation (general purpose registers) ---
        cblock  0xC
            v_ticks
            w_temp
            status_temp
            tmp0
        endc

; --- reset / interrupt vectors ---
        org     0x0000
        goto    main

        org     0x0004
; interrupt service routine
__isr
        movwf   w_temp             ; save context
        swapf   STATUS, w
        movwf   status_temp
        movf    v_ticks, w         ; load ticks
        movwf   tmp0               ; save lhs
        movlw   0x01
        addwf   tmp0, w            ; +
; store ticks
        movwf   v_ticks
        banksel PORTA
        movf    PORTB, w
        xorlw   0x01               ; TOGGLE RB0
        movwf   PORTB
        movlw   0xA0
        banksel INTCON
        movwf   INTCON             ; POKE INTCON
        banksel PORTA
        swapf   status_temp, w     ; restore context
        movwf   STATUS
        swapf   w_temp, f
        swapf   w_temp, w
        retfie


main
; --- digital I/O setup (disable analog/comparators where present) ---
    ifdef CMCON
        banksel CMCON
        movlw   0x07
        movwf   CMCON
    endif
    ifdef CMCON0
        banksel CMCON0
        movlw   0x07
        movwf   CMCON0
    endif
    ifdef ANSEL
        banksel ANSEL
        clrf    ANSEL
    endif
    ifdef ANSELH
        banksel ANSELH
        clrf    ANSELH
    endif
    ifdef ADCON1
        banksel ADCON1
        movlw   0x06
        movwf   ADCON1
    endif
        banksel PORTA
        movlw   0x07
        banksel OPTION_REG
        movwf   OPTION_REG         ; POKE OPTION_REG
        banksel PORTA
        movlw   0xA0
        banksel INTCON
        movwf   INTCON             ; POKE INTCON
        banksel PORTA
; OUTPUT PORTB.0
        banksel TRISB
        bcf     TRISB, 0
        banksel PORTA
        movlw   0x00
; store ticks
        movwf   v_ticks
lbl_idle
        goto    lbl_idle

; end of program: trap here
__halt
        goto    __halt

        END
