; ================================================================
;  Generated by basic2asm  -  BASIC -> MPASM transpiler
;  Target chip : PIC16F628A  (MIDRANGE core)
;  Clock       : 4000 kHz
;  Optimize    : SIZE
;  Flash       : 2048 words   RAM: 96 bytes
; ================================================================

        LIST    p=16f628a
        #include <p16f628a.inc>

; fuse configuration (config word @ 0x2007)
        __CONFIG _XT_OSC & _WDT_OFF & _PWRTE_ON & _MCLRE_ON & _BOREN_OFF & _LVP_OFF & _CP_OFF

; --- RAM allocation (general purpose registers) ---
        cblock  0x20
            v_count
            rt_d0
            rt_d1
            rt_d2
            rt_a
            rt_b
            rt_quot
            rt_rem
            rt_uart_data
            rt_uart_bits
            rt_dec_val
            rt_dec_d
            rt_dec_started
            tmp0
        endc

; --- reset / interrupt vectors ---
        org     0x0000
        goto    main

        org     0x0004
        retfie                     ; no ISR defined


main
; --- digital I/O setup (disable analog/comparators where present) ---
    ifdef CMCON
        banksel CMCON
        movlw   0x07
        movwf   CMCON
    endif
    ifdef CMCON0
        banksel CMCON0
        movlw   0x07
        movwf   CMCON0
    endif
    ifdef ANSEL
        banksel ANSEL
        clrf    ANSEL
    endif
    ifdef ANSELH
        banksel ANSELH
        clrf    ANSELH
    endif
    ifdef ADCON1
        banksel ADCON1
        movlw   0x06
        movwf   ADCON1
    endif
        banksel PORTA
; software UART init: TX=RB2 @ 9600 baud
        banksel PORTA
        bsf     PORTB, 2           ; TX idle high
; OUTPUT PORTB.2
        banksel TRISB
        bcf     TRISB, 2
        banksel PORTA
        movlw   0x00
; store count
        movwf   v_count
lbl_send_loop
        movlw   0x48               ; 'H'
        call    _uart_tx_sw
        movlw   0x65               ; 'e'
        call    _uart_tx_sw
        movlw   0x6C               ; 'l'
        call    _uart_tx_sw
        movlw   0x6C               ; 'l'
        call    _uart_tx_sw
        movlw   0x6F               ; 'o'
        call    _uart_tx_sw
        movlw   0x20               ; ' '
        call    _uart_tx_sw
        movlw   0x66               ; 'f'
        call    _uart_tx_sw
        movlw   0x72               ; 'r'
        call    _uart_tx_sw
        movlw   0x6F               ; 'o'
        call    _uart_tx_sw
        movlw   0x6D               ; 'm'
        call    _uart_tx_sw
        movlw   0x20               ; ' '
        call    _uart_tx_sw
        movlw   0x50               ; 'P'
        call    _uart_tx_sw
        movlw   0x49               ; 'I'
        call    _uart_tx_sw
        movlw   0x43               ; 'C'
        call    _uart_tx_sw
        movlw   0x21               ; '!'
        call    _uart_tx_sw
        movlw   0x20               ; ' '
        call    _uart_tx_sw
        movlw   0x63               ; 'c'
        call    _uart_tx_sw
        movlw   0x6F               ; 'o'
        call    _uart_tx_sw
        movlw   0x75               ; 'u'
        call    _uart_tx_sw
        movlw   0x6E               ; 'n'
        call    _uart_tx_sw
        movlw   0x74               ; 't'
        call    _uart_tx_sw
        movlw   0x3D               ; '='
        call    _uart_tx_sw
        movf    v_count, w         ; load count
        call    _print_dec
        movlw   0x0D               ; CR
        call    _uart_tx_sw
        movlw   0x0A               ; LF
        call    _uart_tx_sw
        movf    v_count, w         ; load count
        movwf   tmp0               ; save lhs
        movlw   0x01
        addwf   tmp0, w            ; +
; store count
        movwf   v_count
; DELAY 1000ms (~1000000 cycles @ 4000kHz)
        movlw   0x45
        movwf   rt_d2
dl0_2
        movlw   0x46
        movwf   rt_d1
dl0_1
        movlw   0x45
        movwf   rt_d0
dl0_0
        decfsz  rt_d0, f
        goto    dl0_0
        decfsz  rt_d1, f
        goto    dl0_1
        decfsz  rt_d2, f
        goto    dl0_2
        goto    lbl_send_loop

; end of program: trap here
__halt
        goto    __halt

; ==================== runtime support ====================

; 8/8 divide: W = rt_a / rt_b (quotient), rt_rem = remainder
_div8
        clrf    rt_quot
        movf    rt_b, f
        btfsc   STATUS, Z
        goto    _div8_zero
        movf    rt_a, w
        movwf   rt_rem
_div8_loop
        movf    rt_b, w
        subwf   rt_rem, w          ; rem - b
        btfss   STATUS, C
        goto    _div8_done
        movwf   rt_rem
        incf    rt_quot, f
        goto    _div8_loop
_div8_done
        movf    rt_quot, w
        return  
_div8_zero
        movlw   0xFF
        movwf   rt_quot
        clrf    rt_rem
        movf    rt_quot, w
        return  

; software UART transmit (8N1) of W on PORTB.2 @ 9600 baud (~104 cyc/bit)
_uart_tx_sw
        movwf   rt_uart_data
        bcf     PORTB, 2           ; start bit
        movlw   0x22
        movwf   rt_d0
_utxd1_0
        decfsz  rt_d0, f
        goto    _utxd1_0
        movlw   0x08
        movwf   rt_uart_bits
_uart_tx_sw_bit
        rrf     rt_uart_data, f    ; LSB -> C
        btfsc   STATUS, C
        bsf     PORTB, 2
        btfss   STATUS, C
        bcf     PORTB, 2
        movlw   0x22
        movwf   rt_d0
_utxb2_0
        decfsz  rt_d0, f
        goto    _utxb2_0
        decfsz  rt_uart_bits, f
        goto    _uart_tx_sw_bit
        bsf     PORTB, 2           ; stop bit
        movlw   0x22
        movwf   rt_d0
_utxs3_0
        decfsz  rt_d0, f
        goto    _utxs3_0
        return  

; print W as unsigned decimal (leading zeros suppressed)
_print_dec
        movwf   rt_dec_val
        clrf    rt_dec_started
        movf    rt_dec_val, w
        movwf   rt_a
        movlw   0x64
        movwf   rt_b
        call    _div8              ; digit = val / 100
        movwf   rt_dec_d
        movf    rt_rem, w
        movwf   rt_dec_val         ; val = val % 100
        movf    rt_dec_d, f
        btfss   STATUS, Z
        goto    _pd_print0         ; non-zero digit
        btfsc   rt_dec_started, 0
        goto    _pd_print0         ; already printing
        goto    _pd_skip0          ; suppress leading zero
_pd_print0
        bsf     rt_dec_started, 0
        movlw   0x30               ; '0'
        addwf   rt_dec_d, w        ; digit -> ASCII
        call    _uart_tx_sw
_pd_skip0
        movf    rt_dec_val, w
        movwf   rt_a
        movlw   0x0A
        movwf   rt_b
        call    _div8              ; digit = val / 10
        movwf   rt_dec_d
        movf    rt_rem, w
        movwf   rt_dec_val         ; val = val % 10
        movf    rt_dec_d, f
        btfss   STATUS, Z
        goto    _pd_print1         ; non-zero digit
        btfsc   rt_dec_started, 0
        goto    _pd_print1         ; already printing
        goto    _pd_skip1          ; suppress leading zero
_pd_print1
        bsf     rt_dec_started, 0
        movlw   0x30               ; '0'
        addwf   rt_dec_d, w        ; digit -> ASCII
        call    _uart_tx_sw
_pd_skip1
        movf    rt_dec_val, w
        movwf   rt_dec_d
        bsf     rt_dec_started, 0
        movf    rt_dec_d, f
        btfss   STATUS, Z
        goto    _pd_print2         ; non-zero digit
        btfsc   rt_dec_started, 0
        goto    _pd_print2         ; already printing
        goto    _pd_skip2          ; suppress leading zero
_pd_print2
        bsf     rt_dec_started, 0
        movlw   0x30               ; '0'
        addwf   rt_dec_d, w        ; digit -> ASCII
        call    _uart_tx_sw
_pd_skip2
        return  

        END
